### ISSUE TITLE
How to translate an dynamic url ?

### ISSUE THREAD

**Issue by joffreyBerrier** [adbrosaci/vue-lang-router#10]
I want to translate this url :  `path: '/house/:id/detail'`

But I don't understand how i can translate them, I have tried three options but nothing works

```json
"house/:id/detail": "maison/:id/coucou"
"houseDetail": "maison/:id/coucou"
"house-detail": "maison/:id/coucou"
```

Any help :) ?

**Comment by radek-altof** [comment]
Hi @joffreyBerrier, you should translate individual parts of URL separately, so probably this is what you're looking for:

```json
{
  "house": "maison",
  "detail": "coucou"
}
```
