### ISSUE TITLE
[intlify] Not found 'nav.home' key in 'en' locale messages.

### ISSUE THREAD

**Issue by qxygene** [adbrosaci/vue-lang-router#27]
You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle.

How to fix this?

**Comment by vAhyThe** [comment]
any progress ?

**Comment by qxygene** [comment]
fixed at 9.2.0-beta.32 so far.
